---

- name: Run the test playbook
  gather_facts: false
  hosts: all
  tasks:
    - name: Get the username running this playbook
      become: false
      local_action: command whoami
      register: username_on_the_host
      
    - name: Display the config
      debug:
      msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
