---

- name: Run the test playbook
  gather_facts: false
  hosts: all
  tasks:
    - name: Get the username running this playbook
      become: false
      local_action: command whoami
      register: username_on_the_host

    - name: Dir list and write to file
      shell:
         " ls -lrt /var/lib/jenkins/workspace/|awk '{print $9}'|sed '/^$/d' > /var/lib/jenkins/workspace/Prince-AnsiblePlaybookExecutionExample/dirlist.txt "
      register: lsout
      tags: lsout
      
    - name: Display the file
      shell: cat /var/lib/jenkins/workspace/Prince-AnsiblePlaybookExecutionExample/dirlist.txt
      register: displaylist
